### ISSUE TITLE
Duplicating HTML output

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#60] opened 2023-05-01 10:55 UTC
I caught it on camera only once, in the beginning, you can ignore the rest of the video https://dl.dropboxusercontent.com/s/y73yppnqyi7yyzz/WindowsTerminal_2023-05-01_12-39-32.mp4

**Comment by jimaek** [comment] 2023-05-09 16:37
Not sure if related but now I am getting this issue. header, metadata, header

```
# go run main.go http https://www.jsdelivr.com --method GET
X-Cached-Since: 2023-05-09T16:31:34+00:00
X-ID: sum-up-gc94
> AS, IN, Vellanur, ASN:36236, NetActuate, Inc
HTTP/1.1 200
Server: nginx
Date: Tue, 09 May 2023 16:33:14 GMT
Content-Type: text/html; charset=utf-8
```

Its also possible that the original issue was fixed on the API side, but needs more testing. 
But this issue is happening right now after the API deploy

**Comment by MartinKolarik** [comment] 2023-05-09 17:13
Looks like part of the issue here might be that we're printing `rawOutput` for in-progress instead of `rawBody`, which would lead to this messed up output. That should be fixed here.

A second issue is we don't actually have the `rawBody` field while the specific probe is in progress, that's up to the API to possibly improve (but the CLI should NOT use the `rawOutput` for the GET case regardless).

**Comment by didil** [comment] 2023-05-10 08:20
in this branch https://github.com/jsdelivr/globalping-cli/pull/66:
- I changed rawOutput => rawBody for the http get in the live output
- I was able to reproduce the duplication issue, it's actually the live printer that fails to completely clear the screen for some reason. I added support for a LIVE_DEBUG=1 env var to demonstrate this. It only prints the live output then clears the screen without printing the full output as usually happens when running the command normally. 
After running `LIVE_DEBUG=1 go run main.go http https://www.jsdelivr.com --method GET` the screen should be empty, but  there are 2 dangling output lines.
![Screenshot 2023-05-10 at 08 53 24](https://github.com/jsdelivr/globalping-cli/assets/1284255/8f55ea5d-120d-421f-970d-24a99edb39bb)
- created an issue in the library's repo to see if they might be able to help https://github.com/pterm/pterm/issues/498

**Comment by MartinKolarik** [comment] 2023-05-10 12:30
Also, the issue is reproducible even with the `v1.0.1` release (but only with the `www.jsdelivr.com` target) so it isn't related to any of the recent changes.

**Comment by MarvinJWendt** [comment] 2023-05-10 23:36
Hi, creator of PTerm here.

After investigating the issue, I found that we had actually looked into this behavior about a year ago, but it had slipped my mind. Unfortunately, the content area cannot exceed the size of the terminal, and updating lines that aren't visible is not possible since the cursor cannot move outside the current viewing area. This is a limitation of how terminals work. However, if `contentHeight < terminalHeight`, then everything should function as expected.

We could potentially implement a View in PTerm that functions similarly to a textbox and responds to user scrolls, but this would require some time to develop. Alternatively, if the content doesn't need to be updated dynamically, it can be printed without the area. Another approach would be to create an alternative screen (virtual temporary terminal) using `fmt.Print("\x1b[?1049h")`. You could then print the content, clear the screen, and print the content again, to update it. However, it's important to keep in mind that alternative screens don't work with every terminal.

Once you're finished with the alternative screen, you can close it by using `fmt.Print("\x1b[?1049l")`. This will clear everything on the screen and return to the original terminal.

Another option would be to use a package that already has dynamic textboxes (like the nano or vim).
I personally like [tview](https://github.com/rivo/tview), it's also the interface library used by K9s.

**Comment by MartinKolarik** [comment] 2023-05-11 00:04
Thanks for the detailed response @MarvinJWendt!

**Closed** 2023-05-16 09:27 UTC
