### ISSUE TITLE
Update goreleaser

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#49] opened 2023-04-12 09:17 UTC
I froze Goreleaser to 1.16 because 1.17 breaks everything. DEB files are not correct and declined by Packagecloud and RPM files use windows slashes \ and fail to install because of that.

Need to find the issue and upgrade back to latest sooner or later

**Comment by jimaek** [comment] 2023-07-08 11:37
@didil can you please check this? I suggest trying to build master on 1.17 to see the broken packages and then upgrade to latest to verify that it fixes them and doesnt break anything new.

After that we could automate winget releases as it requires 1.19 https://github.com/jsdelivr/globalping-cli/issues/4

**Comment by didil** [comment] 2023-07-09 14:50
having a look at this

**Comment by jimaek** [comment] 2023-07-09 17:05
@didil doesnt seem to work https://github.com/jsdelivr/globalping-cli/actions/runs/5500964665/jobs/10024285667

```
Looking for repository at jsdelivr/globalping... success!
Pushing globalping_1.1.1_linux_amd64.deb... error (skipping):
	repository: Debian package parsing error. We weren't able to read your Deb package, which is very odd. Email us so we can figure out why: support@packagecloud.io
Uploading globalping_1.1.1_linux_amd64.deb to raspbian/jessie
Using https://packagecloud.io/ with token:******0c5f
Looking for repository at jsdelivr/globalping... success!
Pushing globalping_1.1.1_linux_amd64.deb... error (skipping):
	repository: Debian package parsing error. We weren't able to read your Deb package, which is very odd. Email us so we can figure out why: support@packagecloud.io
Uploading globalping_1.1.1_linux_amd64.deb to raspbian/stretch
Using https://packagecloud.io/ with token:******0c5f
Looking for repository at jsdelivr/globalping... success!
Pushing globalping_1.1.1_linux_amd64.deb... error (skipping):
	repository: Debian package parsing error. We weren't able to read your Deb package, which is very odd. Email us so we can figure out why: support@packagecloud.io
Uploading globalping_1.1.1_linux_amd64.deb to raspbian/buster
Using https://packagecloud.io/ with token:******0c5f
Looking for repository at jsdelivr/globalping... success!
Pushing globalping_1.1.1_linux_amd64.deb... error (skipping):
	repository: Debian package parsing error. We weren't able to read your Deb package, which is very odd. Email us so we can figure out why: support@packagecloud.io
Uploading globalping_1.1.1_linux_amd64.deb to raspbian/bullseye
```

Can you please check?

**Comment by jimaek** [comment] 2023-07-09 17:07
Its the same error I had with 1.17 and downgrading fixed it. If they didn't fix it by 1.19 then  I think its something wrong on our side

**Comment by didil** [comment] 2023-07-09 17:28
@jimaek it's difficult to say what's happening, with the .deb / .rpm files I have built locally I'm able to push them to a packagecloud repo with the cli.
I would suggest adding a step to the action to upload the globalping_1.1.1_linux_amd64.deb and globalping_1.1.1_linux_amd64.rpm files that are generated to S3 for example so that we can download them and see if there is an issue

**Comment by jimaek** [comment] 2023-07-09 17:33
Ok can you send a PR for that please? Add everything you need to debug the issue

**Comment by didil** [comment] 2023-07-09 17:38
Sure @jimaek do you have an AWS S3 bucket and account we can use for this ?

**Comment by jimaek** [comment] 2023-07-09 17:46
Lets just use something simple like https://0x0.st/
There is no private info involved and it will be a lot quicker to implement

**Comment by jimaek** [comment] 2023-07-09 18:34
And disable all publishing during testing. We dont want test versions to go to chocolately and brew...

**Comment by didil** [comment] 2023-07-10 08:40
@jimaek I'm testing on my fork of the repo. Uploading to 0x0 didn't work, github actions seem to be blocked there:

![Screenshot 2023-07-10 at 09 38 19](https://github.com/jsdelivr/globalping-cli/assets/1284255/b24d37f2-2bfa-461b-a861-3dcf959120e0)

**Comment by jimaek** [comment] 2023-07-10 08:42
There is also `curl -F "file=@test.txt" https://file.io`

**Comment by jimaek** [comment] 2023-07-10 09:25
Good find, let me know how it goes. Maybe we could also fix them as a workflow step if it takes goreleaser too long to fix

**Comment by didil** [comment] 2023-07-24 19:49
@jimaek the issue is fixed in the main branch of goreleaser but they haven't yet made a release that we can use in the github action

**Comment by jimaek** [comment] 2023-07-24 19:52
Ok let's wait

**Closed** 2023-08-10 09:33 UTC
